name: iOS Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.3.app

      - name: Build
        run: |
          xcodebuild clean build -project WeSail.xcodeproj -scheme WeSail -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4"
        # If you're not using a workspace, replace -workspace with -project and specify your .xcodeproj file

      - name: Run tests
        run: |
          xcodebuild test -project WeSail.xcodeproj -scheme WeSail -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4"

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-results
          path: /Users/runner/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
