name: iOS Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.0.app

      - name: Build
        run: |
          set -o pipefail && xcodebuild clean build -project WeSail.xcodeproj -scheme WeSail -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" | xcpretty && exit ${PIPESTATUS[0]}

      - name: Run tests
        run: |
          set -o pipefail && xcodebuild test -project WeSail.xcodeproj -scheme WeSail -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" -verbose | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            /Users/runner/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
            /Users/runner/Library/Developer/Xcode/DerivedData/**/Logs/Build/*.log
